# -- author : ceefar --
# -- file : cicd pipeline yaml - gets fresh nhs data each day from the NHS My Planned Care API --
# -- project : nhs etl 2023 --

name: get_fresh_nhs_data

# -- on schedule and on open pr --
on:
  schedule:
    - cron: "0 */3 * * *" # and every 3 hours
    # - cron: '*/20 * * * *' # run every 20 minutes while testing
    # - cron: "50 06 * * *" # run every day at 5:50am      
    # - cron: "01 01 * * *" # and run every day at 1:01am
  pull_request:
    types: [opened] # on open new pr also  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.2' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: connect to db & run cicd py script # run script to open webpage (and get the latest data)
        env: 
            mysql_db: ${{ secrets.MYSQL_DB }}
            mysql_host: ${{ secrets.MYSQL_HOST }}
            mysql_password: ${{ secrets.MYSQL_PASSWORD }} 
            mysql_port: ${{ secrets.MYSQL_PORT }} 
            mysql_user: ${{ secrets.MYSQL_USER }} 
        run: python core.py
#